#! /usr/bin/env ruby
require "pg"

def display_help
  puts <<~HELP
    An expense recording system

    Commands:

    add AMOUNT MEMO [DATE] - record a new expense
    clear - delete all expenses
    list - list all expenses
    delete NUMBER - remove expense with id NUMBER
    search QUERY - list expenses with a matching memo field
  HELP
end

def list_expenses
  conn = PG.connect(dbname: "expenses")
  result = conn.exec("SELECT * FROM expenses ORDER BY created_on ASC")
  result.each do |tuple|
    columns = [tuple["id"].rjust(3),
               tuple["created_on"].rjust(10),
               tuple["amount"].rjust(12),
               tuple["memo"]]

    puts columns.join(" | ")
  end
end

if ARGV.first&.downcase == "list"
  list_expenses
else
  display_help
end
